# .readthedocs.yaml
version: 2

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

conda:
  environment: environment.yml    # this file lives at repo root

sphinx:
  configuration: docs/conf.py     # adjust path if conf.py elsewhere