version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

conda:
  environment: environment.yml     # not python: / requirements.txt

sphinx:
  configuration: docs/conf.py      # or just conf.py if it's at top level