version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"  # Use mambaforge for faster dependency resolution

conda:
  environment: environment.yml

sphinx:
  configuration: docs/conf.py