name: perspective
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - sphinx
  - ipykernel
  - jinja2
  - pyyaml
  - pip
  - pip:
      - sphinx-book-theme
      - sphinx-fontawesome
      - sphinx-togglebutton